<?php

/**
 * @file
 * Localgov Guides module hooks.
 */

use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function localgov_guides_theme($existing, $type, $theme, $path) {
  return [
    'guides_contents_block' => [
      'variables' => [
        'links' => [],
        'format' => [],
      ],
    ],
    'guides_prev_next_block' => [
      'variables' => [
        'previous_url' => NULL,
        'previous_title' => NULL,
        'next_url' => NULL,
        'next_title' => NULL,
      ],
    ],
    'node__localgov_guides_overview__full' => [
      'template' => 'node--localgov-guides-overview--full',
      'base hook' => 'node',
    ],
    'node__localgov_guides_page__full' => [
      'template' => 'node--localgov-guides-page--full',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function localgov_guides_node_insert(NodeInterface $node) {
  localgov_guides_node_update($node);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * Implements reference back on overview to page when pages are created.
 */
function localgov_guides_node_update(NodeInterface $node) {
  if ($node->bundle() == 'localgov_guides_page') {
    if (
      ($previous = $node->original) &&
      ($previous->localgov_guides_parent->target_id != $node->localgov_guides_parent->target_id)
    ) {
      // There is a previous version of this page.
      // The guide overview it is in isn't the same in the previous and new
      // versions.
      if ($old_parent = $node->original->localgov_guides_parent->entity) {
        // Getting the old guide overview we look for all the references to this
        // page.
        foreach (array_keys($old_parent->localgov_guides_pages->getValue(), ['target_id' => $node->id()]) as $offset) {
          // And remove each reference on the old parent to this page.
          $old_parent->localgov_guides_pages->offsetUnset($offset);
        }
        $old_parent->save();
      }
    }
    if ($parent = $node->localgov_guides_parent->entity) {
      // The current version of this page points to an overview.
      if (array_search(['target_id' => $node->id()], $parent->localgov_guides_pages->getValue()) === FALSE) {
        // The overview does not yet point to this page, so we add it.
        $parent->localgov_guides_pages->appendItem(['target_id' => $node->id()]);
        $parent->save();
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_prepare_form().
 *
 * Check back-reference fields before editing overview.
 */
function localgov_guides_node_prepare_form(NodeInterface $node, $operation, FormStateInterface $form) {
  if ($node->bundle() == 'localgov_guides_overview') {
    localgov_guides_overview_pages_check($node);
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Check back-reference fields before saving.
 * Especially if someone has changed a page since form load!
 */
function localgov_guides_node_presave(NodeInterface $node) {
  if ($node->bundle() == 'localgov_guides_overview') {
    localgov_guides_overview_pages_check($node);
  }
}

/**
 * Check backward references.
 */
function localgov_guides_overview_pages_check(NodeInterface $node) {
  $query = \Drupal::entityQuery('node');
  $query->condition('type', 'localgov_guides_page');
  $query->condition('localgov_guides_parent', $node->id());
  $actual_children = $query->execute();
  $linked_children = array_column($node->localgov_guides_pages->getValue(), 'target_id');
  $missing_children = array_diff($actual_children, $linked_children);
  $extra_children = array_diff($linked_children, $actual_children);
  foreach ($missing_children as $missing) {
    $node->localgov_guides_pages->appendItem(['target_id' => $missing]);
  }
  foreach ($extra_children as $extra) {
    foreach (array_keys($node->localgov_guides_pages->getValue(), ['target_id' => $extra]) as $offset) {
      $node->localgov_guides_pages->offsetUnset($offset);
    }
  }
}

/**
 * Implements hook_modules_installed().
 */
function localgov_guides_modules_installed($modules) {
  $services = in_array('localgov_services_navigation', $modules);
  $topics = in_array('localgov_topics', $modules);
  if ($services || $topics) {
    \Drupal::service('config.installer')->installOptionalConfig();
    localgov_guides_optional_fields_settings($services, $topics);
  }
}

/**
 * Set form settings for optional services and topic fields on installation.
 *
 * @param bool $services
 *   If localgov_services is (being) installed.
 * @param bool $topics
 *   If localgov_topics is (being) installed.
 */
function localgov_guides_optional_fields_settings($services, $topics) {
  $properties = [
    'targetEntityType' => 'node',
    'bundle' => 'localgov_guides_overview',
  ];
  if ($form_displays = \Drupal::entityTypeManager()->getStorage('entity_form_display')->loadByProperties($properties)) {
    foreach ($form_displays as $form_display) {
      assert($form_display instanceof EntityFormDisplayInterface);
      if ($services && !$form_display->getComponent('localgov_services_parent')) {
        $form_display->setComponent('localgov_services_parent', [
          'type' => 'entity_reference_autocomplete',
          'region' => 'content',
          'settings' => [
            'match_operator' => 'CONTAINS',
            'size' => '60',
            'placeholder' => '',
            'match_limit' => 10,
          ],
          'weight' => 51,
        ])->save();
      }
      if ($topics && !$form_display->getComponent('localgov_topics')) {
        $form_display->setComponent('localgov_topic_classified', [
          'type' => 'entity_reference_autocomplete',
          'region' => 'content',
          'settings' => [
            'match_operator' => 'CONTAINS',
            'size' => '60',
            'placeholder' => '',
            'match_limit' => 10,
          ],
          'weight' => 50,
        ])->save();
      }
    }
  }
}
